"""preset values for c3 d1

Revision ID: 17bd5ebc9b02
Revises: b7263ddcafbf
Create Date: 2025-11-05 15:20:19.478073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17bd5ebc9b02'
down_revision: Union[str, Sequence[str], None] = 'b7263ddcafbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trained_models', sa.Column('heat_kernel_size', sa.Integer(), nullable=True))
    op.add_column('trained_models', sa.Column('heat_min_area', sa.Integer(), nullable=True))
    op.add_column('trained_models', sa.Column('heat_threshold', sa.Integer(), nullable=True))
    op.add_column('trained_models', sa.Column('heat_min_intensity', sa.Integer(), nullable=True))
    op.add_column('trained_models', sa.Column('has_preset', sa.SmallInteger(), nullable=False, server_default=sa.text("0")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trained_models', 'heat_min_intensity')
    op.drop_column('trained_models', 'heat_threshold')
    op.drop_column('trained_models', 'heat_min_area')
    op.drop_column('trained_models', 'heat_kernel_size')
    op.drop_column('trained_models', 'has_preset')
    # ### end Alembic commands ###
