"""add deleted flag to all table

Revision ID: 1c895e84c923
Revises: 46c92acd8456
Create Date: 2025-08-07 13:18:47.729399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c895e84c923'
down_revision: Union[str, Sequence[str], None] = '46c92acd8456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trained_models', sa.Column('deleted', sa.SmallInteger(), nullable=False))
    op.add_column('generate_datas', sa.Column('deleted', sa.SmallInteger(), nullable=False))
    op.add_column('detection_results', sa.Column('deleted', sa.SmallInteger(), nullable=False))
    op.add_column('dataset_images', sa.Column('deleted', sa.SmallInteger(), nullable=False))
    op.add_column('alignment_images', sa.Column('deleted', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trained_models', 'deleted')
    op.drop_column('generate_datas', 'deleted')
    op.drop_column('detection_results', 'deleted')
    op.drop_column('dataset_images', 'deleted')
    op.drop_column('alignment_images', 'deleted')
    # ### end Alembic commands ###