"""first db commit

Revision ID: 2b71ae56221e
Revises: 
Create Date: 2025-07-23 11:45:11.541752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b71ae56221e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('logger_name', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('exception_info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('intrinsic_path', sa.Text(), nullable=False),
    sa.Column('bias_path', sa.Text(), nullable=True),
    sa.Column('perspective_path', sa.Text(), nullable=False),
    sa.Column('speed_path', sa.Text(), nullable=False),
    sa.Column('pattern_cols', sa.Integer(), nullable=False),
    sa.Column('pattern_rows', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('name')
    )
    op.create_table('system_config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('work_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sensor_setting_id', sa.Integer(), nullable=False),
    sa.Column('delta_t', sa.Integer(), nullable=False),
    sa.Column('use_roi', sa.Boolean(), nullable=False),
    sa.Column('roi', sa.String(), nullable=True),
    sa.Column('bias_path', sa.Text(), nullable=False),
    sa.Column('sensor_filter', sa.Integer(), nullable=False),
    sa.Column('sensor_filter_threshold', sa.Integer(), nullable=True),
    sa.Column('mask_img_thresh_1', sa.Integer(), nullable=False),
    sa.Column('mask_img_thresh_2', sa.Integer(), nullable=False),
    sa.Column('mask_minimal_area', sa.Integer(), nullable=False),
    sa.Column('skip_frame', sa.Integer(), nullable=True),
    sa.Column('on_event_his_value', sa.Integer(), nullable=False),
    sa.Column('off_event_his_value', sa.Integer(), nullable=False),
    sa.Column('speed_correction_param', sa.Float(), nullable=False),
    sa.Column('colormap', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_setting_id'], ['sensor_settings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('name')
    )
    op.create_table('alignment_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_config_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('alignment_coord', sa.Text(), nullable=False),
    sa.Column('image_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['work_config_id'], ['work_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('work_config_id', sa.Integer(), nullable=False),
    sa.Column('is_trained', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['work_config_id'], ['work_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('name')
    )
    op.create_table('generate_datas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_config_id', sa.Integer(), nullable=False),
    sa.Column('data_dir', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['work_config_id'], ['work_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('image_source_path', sa.Text(), nullable=False),
    sa.Column('usage_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trained_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('epochs', sa.Integer(), nullable=False),
    sa.Column('weight_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('name')
    )
    op.create_table('detection_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('detected_at', sa.String(), nullable=False),
    sa.Column('work_config_id', sa.Integer(), nullable=False),
    sa.Column('trained_model_id', sa.Integer(), nullable=False),
    sa.Column('judgment', sa.Integer(), nullable=False),
    sa.Column('thumbnail_path', sa.Text(), nullable=False),
    sa.Column('his_img_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trained_model_id'], ['trained_models.id'], ),
    sa.ForeignKeyConstraint(['work_config_id'], ['work_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detection_results')
    op.drop_table('trained_models')
    op.drop_table('dataset_images')
    op.drop_table('generate_datas')
    op.drop_table('datasets')
    op.drop_table('alignment_images')
    op.drop_table('work_configs')
    op.drop_table('system_config')
    op.drop_table('sensor_settings')
    op.drop_table('app_logs')
    # ### end Alembic commands ###
