"""add deleted flag

Revision ID: 46c92acd8456
Revises: d74ab0b7dddf
Create Date: 2025-08-07 10:25:15.465501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c92acd8456'
down_revision: Union[str, Sequence[str], None] = 'd74ab0b7dddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('deleted', sa.SmallInteger(), nullable=False))
    op.create_index('datasets_unique_name', 'datasets', ['name'], unique=True, sqlite_where=sa.text('deleted = 0'))
    op.add_column('sensor_settings', sa.Column('deleted', sa.SmallInteger(), nullable=False))
    op.create_index('sensor_settings_unique_name', 'sensor_settings', ['name'], unique=True, sqlite_where=sa.text('deleted = 0'))
    op.add_column('work_configs', sa.Column('deleted', sa.SmallInteger(), nullable=False))
    op.create_index('work_configs_unique_name', 'work_configs', ['name'], unique=True, sqlite_where=sa.text('deleted = 0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('work_configs_unique_name', table_name='work_configs', sqlite_where=sa.text('deleted = 0'))
    op.drop_column('work_configs', 'deleted')
    op.drop_index('sensor_settings_unique_name', table_name='sensor_settings', sqlite_where=sa.text('deleted = 0'))
    op.drop_column('sensor_settings', 'deleted')
    op.drop_index('datasets_unique_name', table_name='datasets', sqlite_where=sa.text('deleted = 0'))
    op.drop_column('datasets', 'deleted')
    # ### end Alembic commands ###
