"""Add new field to Trained Models

Revision ID: 5d1f63fc6e39
Revises: f21135f6c360
Create Date: 2025-08-12 14:16:42.768976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d1f63fc6e39'
down_revision: Union[str, Sequence[str], None] = 'f21135f6c360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trained_models', sa.Column('learn_method', sa.SmallInteger(), nullable=False))
    op.add_column('trained_models', sa.Column('patch_size_1', sa.Integer(), nullable=False))
    op.add_column('trained_models', sa.Column('input_size_1', sa.Integer(), nullable=False))
    op.add_column('trained_models', sa.Column('weight_path_1', sa.Text(), nullable=False))
    op.add_column('trained_models', sa.Column('patch_size_2', sa.Integer(), nullable=True))
    op.add_column('trained_models', sa.Column('input_size_2', sa.Integer(), nullable=True))
    op.add_column('trained_models', sa.Column('weight_path_2', sa.Text(), nullable=True))
    op.create_index('trained_models_unique_name', 'trained_models', ['name'], unique=True, sqlite_where=sa.text('deleted = 0'))
    op.drop_column('trained_models', 'weight_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trained_models', sa.Column('weight_path', sa.TEXT(), nullable=False))
    op.drop_index('trained_models_unique_name', table_name='trained_models', sqlite_where=sa.text('deleted = 0'))
    op.drop_column('trained_models', 'weight_path_2')
    op.drop_column('trained_models', 'input_size_2')
    op.drop_column('trained_models', 'patch_size_2')
    op.drop_column('trained_models', 'weight_path_1')
    op.drop_column('trained_models', 'input_size_1')
    op.drop_column('trained_models', 'patch_size_1')
    op.drop_column('trained_models', 'learn_method')
    # ### end Alembic commands ###
