"""add seg_padding

Revision ID: 61fb7cd2034a
Revises: 65cf3ecdaba7
Create Date: 2025-11-07 11:28:32.551359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61fb7cd2034a'
down_revision: Union[str, Sequence[str], None] = '65cf3ecdaba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_configs', sa.Column('seg_padding', sa.Integer(), nullable=False, server_default='20'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_configs', 'seg_padding')
    # ### end Alembic commands ###
