"""add histogram_path in work configs

Revision ID: b55ce7bbc9e6
Revises: b934ff2bd757
Create Date: 2026-01-20 15:12:27.468679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55ce7bbc9e6'
down_revision: Union[str, Sequence[str], None] = 'b934ff2bd757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_configs', sa.Column('histogram_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_configs', 'histogram_path')
    # ### end Alembic commands ###
