"""add engine path

Revision ID: b934ff2bd757
Revises: 3bc9d20a393f
Create Date: 2026-01-15 16:05:33.450369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b934ff2bd757'
down_revision: Union[str, Sequence[str], None] = '3bc9d20a393f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trained_models', sa.Column('engine_path_1', sa.Text(), nullable=True))
    op.add_column('trained_models', sa.Column('engine_path_2', sa.Text(), nullable=True))

    op.execute(
        sa.text(
            "UPDATE trained_models "
            "SET engine_path_1 = weight_path_1 "
            "WHERE engine_path_1 IS NULL"
        )
    )

    with op.batch_alter_table('trained_models') as batch_op:
        batch_op.alter_column('engine_path_1', existing_type=sa.Text(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trained_models', 'engine_path_2')
    op.drop_column('trained_models', 'engine_path_1')
    # ### end Alembic commands ###
