"""add created updated deleted for alignment images

Revision ID: d74ab0b7dddf
Revises: 2b71ae56221e
Create Date: 2025-07-28 14:02:20.314177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74ab0b7dddf'
down_revision: Union[str, Sequence[str], None] = '2b71ae56221e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alignment_images', sa.Column('created_at', sa.String(), nullable=False))
    op.add_column('alignment_images', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('alignment_images', sa.Column('deleted_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alignment_images', 'deleted_at')
    op.drop_column('alignment_images', 'updated_at')
    op.drop_column('alignment_images', 'created_at')
    # ### end Alembic commands ###
