"""add heatmap_path

Revision ID: f80a47f11ff1
Revises: db9bcd1c8a20
Create Date: 2025-08-27 17:26:22.865337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80a47f11ff1'
down_revision: Union[str, Sequence[str], None] = 'db9bcd1c8a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column nullable
    op.add_column('detection_results', sa.Column('heatmap_path', sa.Text(), nullable=True))

    # Backfill values from thumbnail_path
    op.execute("""
        UPDATE detection_results
        SET heatmap_path = thumbnail_path
        WHERE thumbnail_path IS NOT NULL
    """)

    # Alter to NOT NULL
    with op.batch_alter_table("detection_results", schema=None) as batch_op:
        batch_op.alter_column(
            "heatmap_path",
            existing_type=sa.Text(),
            nullable=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection_results', 'heatmap_path')
    # ### end Alembic commands ###
