"""Default values for the application"""

class DefaultCommon:
    """DefaultCommon"""
    LANGUAGES_CODE = {
        "日本語": "ja",
        "Tiếng Việt": "vi"
    }

class DefaultAnimation:
    """DefaultAnimation"""
    SCROLL_DURATION = 0.4
    SCROLL_TRANSITION = "out_quart"
    HOVER_DURATION = 0.15
    HOVER_TRANSITION = "out_quart"
    EDGE_SNAP_THRESHOLD = 0.1

class DefaultValuesA1:
    """DefaultValuesA1"""

class DefaultValuesB1:
    """DefaultValuesB1"""
    B_SETTING_NAME = ''
    B_SETTING_NAME_MAX_LENGTH = 100
    B_SETTING_NAME_REQUIRED = True

    PROPHESEE_SETTING = ''
    PROPHESEE_SETTING_REQUIRED = True

    DELTA_T = 15000
    DELTA_T_MIN_VALUE = 1
    DELTA_T_MAX_VALUE = 100000
    DELTA_T_REQUIRED = True

    B_BIAS_PATH_SELECT = ''
    B_BIAS_PATH_SELECT_REQUIRED = True

    I_ROI_CHECKBOX = True

    ROI_TOP_LEFT_X = ''
    ROI_TOP_LEFT_X_MIN_VALUE = 0
    ROI_TOP_LEFT_X_MAX_VALUE = 1280
    ROI_TOP_LEFT_X_REQUIRED = True

    ROI_TOP_LEFT_Y = ''
    ROI_TOP_LEFT_Y_MIN_VALUE = 0
    ROI_TOP_LEFT_Y_MAX_VALUE = 720
    ROI_TOP_LEFT_Y_REQUIRED = True

    ROI_BOTTOM_RIGHT_X = ''
    ROI_BOTTOM_RIGHT_X_MIN_VALUE = 0
    ROI_BOTTOM_RIGHT_X_MAX_VALUE = 1280
    ROI_BOTTOM_RIGHT_X_REQUIRED = True

    ROI_BOTTOM_RIGHT_Y = ''
    ROI_BOTTOM_RIGHT_Y_MIN_VALUE = 0
    ROI_BOTTOM_RIGHT_Y_MAX_VALUE = 720
    ROI_BOTTOM_RIGHT_Y_REQUIRED = True

    SENSOR_FILTER = 'None'

    SENSOR_FILTER_THRESHOLD = 50000
    SENSOR_FILTER_THRESHOLD_MIN_VALUE = 1
    SENSOR_FILTER_THRESHOLD_MAX_VALUE = 100000

    ON_EVENT_HIS_VALUE = 5
    ON_EVENT_HIS_VALUE_MIN_VALUE = -255
    ON_EVENT_HIS_VALUE_MAX_VALUE = 255
    ON_EVENT_HIS_VALUE_REQUIRED = True

    OFF_EVENT_HIS_VALUE = 5
    OFF_EVENT_HIS_VALUE_MIN_VALUE = -255
    OFF_EVENT_HIS_VALUE_MAX_VALUE = 255
    OFF_EVENT_HIS_VALUE_REQUIRED = True

    SEG_KERNEL_SIZE = 5
    SEG_KERNEL_SIZE_MIN_VALUE = 1
    SEG_KERNEL_SIZE_MAX_VALUE = 35
    SEG_KERNEL_SIZE_REQUIRED = True

    SEG_THRESHOLD = 50
    SEG_THRESHOLD_MIN_VALUE = 1
    SEG_THRESHOLD_MAX_VALUE = 255
    SEG_THRESHOLD_REQUIRED = True

    SEG_PADDING = 20
    SEG_PADDING_MIN_VALUE = 1
    SEG_PADDING_MAX_VALUE = 1000
    SEG_PADDING_REQUIRED = True

    HISTOGRAM_ADD_PIXEL_PARAMS = 1.0
    HISTOGRAM_ADD_PIXEL_PARAMS_MIN_VALUE = 0.5
    HISTOGRAM_ADD_PIXEL_PARAMS_MAX_VALUE = 1.5
    HISTOGRAM_ADD_PIXEL_PARAMS_REQUIRED = True

    COLOR_MAP = 'JET'
    COLOR_MAP_REQUIRED = False

    ALIGNMENT_1_REQUIRED = True
    ALIGNMENT_2_REQUIRED = False
    ALIGNMENT_3_REQUIRED = False
    HIDE_ALIGNMENT_WINDOW = False

class DefaultValuesB2:
    """DefaultValuesB2"""
    SELECT_SETTINGS_REQUIRED = True
    FOLDER_SELECT_REQUIRED = True
    NEW_FOLDER_NAME_MAX_LENGTH = 100

class DefaultValuesC1:
    """DefaultValuesC1"""

class DefaultValuesC2:
    """DefaultValuesC2"""

class DefaultValuesC3:
    """DefaultValuesC3"""
    C3_BLUR_INPUT = "1"
    C3_BLUR_INPUT_STEP = 2
    C3_BLUR_INPUT_MIN_VALUE = 1
    C3_BLUR_INPUT_MAX_VALUE = 35
    C3_BLUR_INPUT_REQUIRED = True

    C3_MIN_AREA_INPUT = "0"
    C3_MIN_AREA_INPUT_MIN_VALUE = 0
    C3_MIN_AREA_INPUT_MAX_VALUE = 1000
    C3_MIN_AREA_INPUT_REQUIRED = True

    C3_THRESHOLD_INPUT = "0"
    C3_THRESHOLD_INPUT_MIN_VALUE = 0
    C3_THRESHOLD_INPUT_MAX_VALUE = 255
    C3_THRESHOLD_INPUT_REQUIRED = True
    C3_THRESHOLD_INPUT_SHOW_COLOR = True

    C3_EVENT_INTENSITY_INPUT = "0"
    C3_EVENT_INTENSITY_INPUT_MIN_VALUE = 0
    C3_EVENT_INTENSITY_INPUT_MAX_VALUE = 10000000
    C3_EVENT_INTENSITY_INPUT_REQUIRED = True

    C3_DATASET_SELECT = ""
    C3_DATASET_SELECT_REQUIRED = True

    C3_PREVIEW_LEFT_RATIO = 861.141
    C3_PREVIEW_RIGHT_RATIO = 350

    C3_TRANSPARENCY_SLIDER_INPUT = 0.5
    C3_TRANSPARENCY_SLIDER_STEP = 0.05
    C3_TRANSPARENCY_SLIDER_MIN_VALUE = 0
    C3_TRANSPARENCY_SLIDER_MAX_VALUE = 1

class DefaultValuesD1:
    """DefaultValuesD1"""
    SELECT_MODEL_REQUIRED = True

    HEAT_KERNEL_SIZE = 1
    HEAT_KERNEL_SIZE_MIN_VALUE = 1
    HEAT_KERNEL_SIZE_MAX_VALUE = 35
    HEAT_KERNEL_SIZE_REQUIRED = True

    HEAT_THRESHOLD = 128
    HEAT_THRESHOLD_MIN_VALUE = 0
    HEAT_THRESHOLD_MAX_VALUE = 255
    HEAT_THRESHOLD_REQUIRED = True

    HEAT_MIN_AREA = 50
    HEAT_MIN_AREA_MIN_VALUE = 0
    HEAT_MIN_AREA_MAX_VALUE = 1000
    HEAT_MIN_AREA_REQUIRED = True

    HEAT_MIN_INTENSITY = 10000000
    HEAT_MIN_INTENSITY_MIN_VALUE = 0
    HEAT_MIN_INTENSITY_MAX_VALUE = 10000000
    HEAT_MIN_INTENSITY_REQUIRED = True

class DefaultValuesD2:
    """DefaultValuesD2"""
    # No default values atm

class DefaultValuesE:
    """DefaultValuesE"""
    #Note: All init values are defined in env
    DOT_POINT_MIN_VALUE = 0
    DOT_POINT_MAX_VALUE = 1
    DOT_POINT_REQUIRED = False

    DETECT_AREA_SPLIT_REQUIRED = False

    BACKUP_PATH_REQUIRED = False

    SHOW_IMAGE_WINDOW_WIDTH_MIN_VALUE = 0
    SHOW_IMAGE_WINDOW_WIDTH_MAX_VALUE = 1920
    SHOW_IMAGE_WINDOW_WIDTH_REQUIRED = True
    SHOW_IMAGE_WINDOW_HEIGHT_MIN_VALUE = 0
    SHOW_IMAGE_WINDOW_HEIGHT_MAX_VALUE = 1280
    SHOW_IMAGE_WINDOW_HEIGHT_REQUIRED = True

    SHOW_HIS_IMAGE_WINDOW_WIDTH_MIN_VALUE = 0
    SHOW_HIS_IMAGE_WINDOW_WIDTH_MAX_VALUE = 1920
    SHOW_HIS_IMAGE_WINDOW_WIDTH_REQUIRED = True
    SHOW_HIS_IMAGE_WINDOW_HEIGHT_MIN_VALUE = 0
    SHOW_HIS_IMAGE_WINDOW_HEIGHT_MAX_VALUE = 1280
    SHOW_HIS_IMAGE_WINDOW_HEIGHT_REQUIRED = True

    INPUT_SIZE_LIST_REQUIRED = True
    PATCH_SIZE_LIST_REQUIRED = True

    AUTO_CLEANER_CHECKBOX_DEFAULT = False

    AUTO_CLEANER_DAYS_TO_KEEP_REQUIRED = True
    AUTO_CLEANER_DAYS_TO_KEEP = "" # Display empty
    AUTO_CLEANER_DAYS_TO_KEEP_MIN_VALUE = 1
    AUTO_CLEANER_DAYS_TO_KEEP_MAX_VALUE = 999

class DefaultValuesTable:
    """DefaultValuesTable"""
    MAX_VISIBLE_PAGES = 7
    EDGE_PAGES = 1  # Number of pages to show at start/end
    SURROUNDING_PAGES = 2  # Number of pages to show around current page
    ELLIPSIS = '...'
